### PR TITLE
Misc doc changes

### PR DESCRIPTION
**Pull request by kianmeng**
Besides misc doc changes, this PR updates and clean up the HTML
documentation.

### CODE REVIEW

**Comment by kianmeng** [comment]
@benwilson512 Should I resolve the conflict or resubmit the PR?

**Comment by mcrumm** [comment]
Hi @kianmeng! I wanted to get a release published before adding any more PRs, but yours probably should have been included in 0.4.0, sorry about that! Feel free to resolve conflicts on this PR and we will get it merged :)

**Comment by kianmeng** [comment]
@mcrumm Done. Please check.

**Comment by mcrumm** [comment]
🍬 🍬 🍬 🍬 🍬

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
