### PR TITLE
Update Travis CI build matrix

### PR DESCRIPTION
**Pull request by sgerrand**
💁 These changes to the Travis CI build matrix:
* add Elixir 1.11
* add Erlang/OTP 23
* exclude known incompatible Elixir & OTP version pairs

### CODE REVIEW

**Comment by sgerrand** [comment]
🏁 Build results for these changes are available: https://travis-ci.com/github/sgerrand/briefly/builds/221034980

**Comment by sgerrand** [comment]
👋 @benwilson512: Would you please review these changes when you can.

**Comment by benwilson512** [comment]
I think we should remove Elixir versions older than 1.9, we have no intention of supporting issues with Elixir versions older than that.

**Comment by sgerrand** [comment]
I've removed Elixir versions prior to 1.9 from the build matrix. The supported `project.elixir` version in `mix.exs` should probably be updated to reflect this as well, but I'll defer to you on whether that should happen as part of this changeset or not.

**Comment by sgerrand** [comment]
👋 @benwilson512: I've added 0ddd76e to address your request. Would you please review these changes when you can.

**Comment by benwilson512** [comment]
Thank you!

**Pull request merged**
